---
engines:
  pep8:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
    - "**.py"
    - "**.js"
    - "**.css"
exclude_paths:
  - tests/