---
engines:
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
    - "**.py"
exclude_paths:
  - tests/
  - "**.js"
  - "**.css"
  - "**.map"