---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.py"
exclude_paths:
- tests/