language: python
python:
  - '3.5'
  - 'nightly'
install:
  - pip install -e .
  - pip install -r requirements.txt
script:
  - codeclimate-test-reporter before-build
  - pycodestyle --show-source --ignore=E501,E402  ./
  - cp config.txt.inc config.txt
  - py.test --cov=footyhints tests
  - codeclimate-test-reporter
