language: python
sudo: required
services:
  - docker
branches:
  # Restrict push builds to only master
  only:
  - master
before_install:
  # Fail immediately on any error
  - set -e
install:
  # Install newer version of docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` -o docker-compose
  - chmod +x docker-compose
  - export PATH=./:$PATH
  # Build containers needed for tests only
  - make build-tests
before_script:
  # Prep codeclimate reporting
  - docker run -it
      -e GIT_BRANCH=$TRAVIS_BRANCH
      -e GIT_COMMIT_SHA=$TRAVIS_COMMIT
      -e GIT_COMMITTED_AT=$(git log -1 --pretty=tformat:%ct $TRAVIS_COMMIT)
      -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
      footyhints/tester:latest bash -c
    "/usr/bin/cc-test-reporter before-build"
script:
  - make run-tests
after_script:
  # Push results to code climate
  # only if a non PR and branch is master
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      docker run -it \
        -v artifacts:/opt/footyhints/env/artifacts \
        -e GIT_BRANCH=$TRAVIS_BRANCH \
        -e GIT_COMMIT_SHA=$TRAVIS_COMMIT \
        -e GIT_COMMITTED_AT=$(git log -1 --pretty=tformat:%ct $TRAVIS_COMMIT) \
        -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID \
        footyhints/tester:latest bash -c \
      "cp artifacts/coverage.xml ./ && /usr/bin/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    fi
