language: python
python:
  - '3.5'
  - 'nightly'
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - flake8 --config .flake8 ./
  - cp config.txt.inc config.txt
  - py.test --cov=footyhints tests
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
