language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
install: "pip install -e ."
script:
  - py.test --cov=footyhints tests
  - codeclimate-test-reporter
  - pycodestyle --show-source --ignore=E501,E402  ./
