---
version: '3.7'
services:
  nginx:
    image: footyhints/nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      cache_from:
        - footyhints/nginx:latest
    depends_on:
      - flask
    networks:
      - default
    ports:
      - 80:80
    restart: always
  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=footyhints
      - MYSQL_USER=footyhints_user
      - MYSQL_PASSWORD=CHANGEME
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    # ports:
    #   - 3306:3306
    restart: always
  base:
    image: footyhints/base:latest
    build:
      context: .
      dockerfile: ./docker/base/Dockerfile
      cache_from:
        - footyhints/base:latest
    restart: "no"
  bootstrap:
    image: footyhints/bootstrap:latest
    build:
      context: .
      dockerfile: ./docker/bootstrap/Dockerfile
      cache_from:
        - footyhints/bootstrap:latest
    depends_on:
      - base
    networks:
      - default
    restart: on-failure
  flask:
    image: footyhints/flask:latest
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
      cache_from:
        - footyhints/flask:latest
    depends_on:
      - bootstrap
    networks:
      - default
    restart: always
  cron:
    image: footyhints/cron:latest
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
      cache_from:
        - footyhints/cron:latest
    depends_on:
      - bootstrap
    networks:
      - default
    restart: always

volumes:
  mysql:

networks:
  default:
