# Generated by Django 3.1.1 on 2021-02-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_game_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='match_day',
        ),
    ]
