# Generated by Django 3.1.1 on 2021-02-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_game_match_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='interest_level',
            field=models.TextField(null=True),
        ),
    ]
