# Generated by Django 3.1.1 on 2021-02-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_game_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo_image',
            field=models.ImageField(null=True, upload_to='web/static/images/dynamic/competitions', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_image',
            field=models.ImageField(null=True, upload_to='web/static/images/dynamic/teams', verbose_name='img'),
        ),
    ]
