# Generated by Django 3.1.1 on 2021-02-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210216_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo_image',
            field=models.ImageField(default='web/static/images/default_competition_logo.png', upload_to='web/static/images/dynamic/competitions', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_image',
            field=models.ImageField(default='web/static/images/default_team_logo.png', upload_to='web/static/images/dynamic/teams', verbose_name='img'),
        ),
    ]
