# Generated by Django 3.1.1 on 2021-02-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210216_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
