# Generated by Django 3.1.1 on 2021-03-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210315_2314'),
        ('web', '0011_auto_20210315_2250'),
    ]

    operations = [
    ]
