# Generated by Django 3.1.1 on 2021-03-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_merge_20210316_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
