# Generated by Django 3.1.6 on 2021-04-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_question_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='highlights_url',
            field=models.TextField(null=True),
        ),
    ]
