# Generated by Django 3.2.1 on 2021-05-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210504_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
