---
kind: ConfigMap
apiVersion: v1
metadata:
  name: footyhints-configmap
  namespace: footyhints
data:
  FOOTYHINTS_MODE: "development"
  FOOTYHINTS_WEB_DEBUG: "False"
  FOOTYHINTS_DB_URI: "mysql://footyhints_user:MYSQL_PASSWORD_PLACEHOLDER@mysql/footyhints"
  MYSQL_DATABASE: "footyhints"
  MYSQL_USER: "footyhints_user"
  MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD_PLACEHOLDER"
  MYSQL_PASSWORD: "MYSQL_PASSWORD_PLACEHOLDER"
