---
apiVersion: v1
kind: Namespace
metadata:
  name: footyhints

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: footyhints-configmap
  namespace: footyhints
data:
  FOOTYHINTS_MODE: "production"
  FOOTYHINTS_WEB_DEBUG: "False"
  FOOTYHINTS_API_KEY: "FOOTYHINTS_API_KEY_PLACEHOLDER"
  FOOTYHINTS_VERSION: "FOOTYHINTS_VERSION_PLACEHOLDER"
  FOOTYHINTS_DB_URI: "mysql://footyhints_user:MYSQL_PASSWORD_PLACEHOLDER@mysql/footyhints"
  FOOTYHINTS_FETCH_LEAGUE_COUNTRY: "England"
  FOOTYHINTS_FETCH_LEAGUE_NAME: "Premier League"
  MYSQL_DATABASE: "footyhints"
  MYSQL_USER: "footyhints_user"
  MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD_PLACEHOLDER"
  MYSQL_PASSWORD: "MYSQL_PASSWORD_PLACEHOLDER"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: footyhints
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: footyhints/footyhints_flask:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 5000
            protocol: TCP
          envFrom:
            - configMapRef:
                name: footyhints-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  namespace: footyhints
spec:
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
        - name: cron
          image: footyhints/footyhints_cron:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: footyhints-configmap
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap
  namespace: footyhints
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        - name: bootstrap
          image: footyhints/footyhints_bootstrap:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: footyhints-configmap
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: footyhints
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5
          imagePullPolicy: Always
          ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
          envFrom:
            - configMapRef:
                name: footyhints-configmap

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: footyhints
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: footyhints/footyhints_nginx:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 80
            protocol: TCP

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: footyhints
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
  type: NodePort

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: flask
  namespace: footyhints
  labels:
    app: flask
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: flask

---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: footyhints
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql

---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: footyhints-com-cert
  namespace: footyhints
spec:
  domains:
    - footyhints.com

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: footyhints
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "footyhints-com-ip"
    networking.gke.io/managed-certificates: "footyhints-com-cert"
spec:
  backend:
    serviceName: nginx
    servicePort: 80
