---
version: '3.7'
services:
  mysql:
    image: mysql:8
    restart: on-failure
    networks:
      - default
    env_file: tests.env
  redis:
    image: redis:latest
    restart: on-failure
    networks:
      - default
  tester:
    image: footyhints/footyhints_tester:latest
    build:
      context: ../
      dockerfile: ./docker/tester/Dockerfile
      cache_from:
        - footyhints/footyhints_tester:latest
    command: bash -c 'exit 0'
    depends_on:
      - mysql
    networks:
      - default
    restart: "no"
    env_file: tests.env
networks:
  default:
