---
version: '3.7'
services:
  mysql:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 30s
      timeout: 3s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql
    # ports:
    #   - 3306:3306
    networks:
      - default
    restart: always
    env_file: footyhints.env
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "ping"]
      interval: 30s
      timeout: 3s
      retries: 10
    # ports:
    #   - 6379:6379
    networks:
      - default
    restart: always
  bootstrap:
    image: footyhints/footyhints_bootstrap:latest
    healthcheck:
      test: ["CMD", "pgrep", "python"]
      interval: 3s
      timeout: 30s
      retries: 10
    volumes:
      - web_static:/opt/footyhints/envs/footyhints/web/static
    networks:
      - default
    restart: on-failure
    env_file: footyhints.env
  cron:
    image: footyhints/footyhints_cron:latest
    healthcheck:
      test: ["CMD", "pgrep", "/usr/sbin/cron", "-f"]
      interval: 30s
      timeout: 30s
      retries: 10
    depends_on:
      - bootstrap
    networks:
      - default
    restart: always
    env_file: footyhints.env
  nginx:
    image: footyhints/footyhints_nginx:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:80"]
      interval: 30s
      timeout: 3s
      retries: 10
    depends_on:
      - web
    volumes:
      - web_static:/web_static
      - live_ssl:/etc/nginx/ssl/live/
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    restart: always
  web:
    image: footyhints/footyhints_web:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000"]
      interval: 30s
      timeout: 3s
      retries: 10
    depends_on:
      - bootstrap
    volumes:
      - web_static:/opt/footyhints/envs/footyhints/web/static
    networks:
      - default
    restart: always
    env_file: footyhints.env


volumes:
  mysql:
  web_static:
  live_ssl:

networks:
  default:
