---
version: '3.7'
services:
  mysql:
    image: mysql:5
    restart: on-failure
    networks:
      - default
    env_file: tests.env
  base:
    image: footyhints/base:latest
    build:
      context: ../
      dockerfile: ./docker/base/Dockerfile
      cache_from:
        - footyhints/base:latest
    restart: "no"
  tester:
    image: footyhints/tester:latest
    build:
      context: ../
      dockerfile: ./docker/tester/Dockerfile
      cache_from:
        - footyhints/tester:latest
    command: bash -c 'exit 0'
    depends_on:
      - base
      - mysql
    networks:
      - default
    restart: "no"
    env_file: tests.env
networks:
  default:
