---
version: '3.7'
services:
  nginx:
    image: footyhints/footyhints_nginx:latest
    depends_on:
      - flask
    networks:
      - default
    ports:
      - 80:80
    restart: always
  mysql:
    image: mysql:8
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    # ports:
    #   - 3306:3306
    restart: always
    env_file: footyhints.env
  bootstrap:
    image: footyhints/footyhints_bootstrap:latest
    networks:
      - default
    restart: on-failure
    env_file: footyhints.env
  flask:
    image: footyhints/footyhints_flask:latest
    depends_on:
      - bootstrap
    networks:
      - default
    restart: always
    env_file: footyhints.env
  cron:
    image: footyhints/footyhints_cron:latest
    depends_on:
      - bootstrap
    networks:
      - default
    restart: always
    env_file: footyhints.env

volumes:
  mysql:

networks:
  default:
