---
version: '2.2'
services:
  base:
    build:
      context: ../
      dockerfile: docker/base/Dockerfile
  bootstrap:
    build:
      context: ../
      dockerfile: docker/bootstrap/Dockerfile
    command: /app/bin/setup_db
    depends_on:
      - base
    volumes:
      - data:/app/data
  flask:
    build:
      context: ../
      dockerfile: docker/flask/Dockerfile
    command: python /app/run.py
    depends_on:
      - bootstrap
    volumes:
      - data:/app/data
    networks:
      - default
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - flask
    command: /usr/sbin/nginx
    networks:
      - default
    ports:
      - 80:80

  # cron:
  #   build:
  #     context: ../
  #     dockerfile: docker/cron/Dockerfile
  #   depends_on:
  #     - bootstrap
  #   command: cron -f
  #   volumes:
  #     - data:/app/data
  #   networks:
  #     - default


volumes:
  data:

networks:
  default: