---
version: '3.7'
services:
  mysql:
    image: mysql:8
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    # ports:
    #   - 3306:3306
    restart: always
    env_file: footyhints.env
  bootstrap:
    image: footyhints/footyhints_bootstrap:latest
    networks:
      - default
    restart: on-failure
    env_file: footyhints.env
  cron:
    image: footyhints/footyhints_cron:latest
    depends_on:
      - bootstrap
    networks:
      - default
    restart: always
    env_file: footyhints.env
  nginx:
    image: footyhints/footyhints_nginx:latest
    depends_on:
      - web
    volumes:
      - web_static:/web_static
    networks:
      - default
    ports:
      - 80:80
    restart: always
  web:
    image: footyhints/footyhints_web:latest
    depends_on:
      - bootstrap
    volumes:
      - web_static:/opt/footyhints/envs/footyhints/web/static
    networks:
      - default
    restart: always
    env_file: footyhints.env


volumes:
  mysql:
  web_static:

networks:
  default:
