name: Dev

on:
  push:
    branches: 'master'

jobs:
  deploy-dev:
    name: Deploy Development Environment
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Set version from latest commit hash
    - name: Set VERSION env
      run: echo ::set-env name=VERSION::$(git log -1 --pretty=%h)

    - name: Write ssh key
      run: |
        echo -e "${{ secrets.FOOTYHINTS_SSH_KEY }}" >> ~/footyhints
        chmod 600 ~/footyhints

    - name: Run setup and install commands
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=no" ${{ secrets.FOOTYHINTS_SSH_USER_DEV }}@${{ secrets.FOOTYHINTS_SSH_HOST_DEV }} "

          # Remove previous environment
          rm -rf /footyhints || true

          # Setup new environment
          git clone https://github.com/pwnbus/footyhints /footyhints
          cd /footyhints
          git checkout $VERSION

          # Overwrite specific environment vars
          echo \"\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_MODE=development\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_WEB_DEBUG=False\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_SECRET_KEY=${{ secrets.FOOTYHINTS_SECRET_KEY_DEV }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_FETCH_LEAGUE_COUNTRY=England\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_FETCH_LEAGUE_NAME=Premier League\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD_DEV }}\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_DATABASE=footyhints\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_USER=${{ secrets.MYSQL_USER_DEV }}\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD_DEV }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_DB_URI=mysql://${{ secrets.MYSQL_USER_DEV }}:${{ secrets.MYSQL_PASSWORD_DEV }}@mysql/footyhints\" >> /footyhints/docker/footyhints.env

          # Build and run
          make build clean run

          # Cleanup
          rm -rf /footyhints
        "

    - name: Cleanup
      run: rm -rf ~/footyhints
