name: DockerHub
on:
  push:
    branches:
      - master

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: make login-dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build images
      run: make build-release-images

    - name: Push images to DockerHub
      run: make push-release-images
