name: Production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-prod:
    name: Deploy Production Environment
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Set version to latest tag
    - name: Set VERSION env
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Write ssh key
      run: |
        echo -e "${{ secrets.FOOTYHINTS_SSH_KEY }}" >> ~/footyhints
        chmod 600 ~/footyhints

    - name: Run setup and install commands
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=no" root@${{ secrets.FOOTYHINTS_SSH_HOST_PROD }} "

          # Remove previous environment
          rm -rf /footyhints || true

          # Setup new environment
          git clone https://github.com/pwnbus/footyhints /footyhints
          cd /footyhints
          git checkout $VERSION

          # Overwrite specific environment vars
          echo \"\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_MODE=production\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_WEB_DEBUG=False\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_API_KEY=${{ secrets.FOOTYHINTS_API_KEY }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_SECRET_KEY=${{ secrets.FOOTYHINTS_SECRET_KEY_PROD }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_GOOGLE_ANALYTICS_KEY=${{ secrets.FOOTYHINTS_GOOGLE_ANALYTICS_KEY }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_FETCH_LEAGUE_COUNTRY=England\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_FETCH_LEAGUE_NAME=Premier League\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD_PROD }}\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_DATABASE=footyhints\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_USER=${{ secrets.MYSQL_USER_PROD }}\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD_PROD }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_DB_URI=mysql://${{ secrets.MYSQL_USER_PROD }}:${{ secrets.MYSQL_PASSWORD_PROD }}@mysql/footyhints\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_VERSION=$VERSION\" >> /footyhints/docker/footyhints.env

          # Build and run
          make build clean run

          # Cleanup
          rm -rf /footyhints
        "

    - name: Cleanup
      run: rm -rf ~/footyhints
