name: Production

on:
  push:
    tags:
      - 'v*.*.*'
  # Allow for manual run via github
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy Production Environment
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Set version to latest tag
    - name: Set VERSION env
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Write ssh key
      run: |
        echo -e "${{ secrets.FOOTYHINTS_SSH_KEY }}" >> ~/footyhints
        chmod 600 ~/footyhints

    - name: Purge old builds on remote host
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=accept-new" root@${{ secrets.FOOTYHINTS_SSH_HOST_PROD }} "
          docker system prune -f
        "

    - name: Run repo setup on remote host
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=accept-new" root@${{ secrets.FOOTYHINTS_SSH_HOST_PROD }} "
          # Remove previous environment
          rm -rf /footyhints || true

          # Setup new environment
          git clone git@github.com:pwnbus/footyhints.git /footyhints
          cd /footyhints
          git checkout $VERSION

          # Overwrite specific environment vars
          echo \"\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_MODE=production\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_WEB_DEBUG=False\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_API_KEY=${{ secrets.FOOTYHINTS_API_KEY }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_SECRET_KEY=${{ secrets.FOOTYHINTS_SECRET_KEY_PROD }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_CACHE_ENABLED=${{ secrets.FOOTYHINTS_CACHE_ENABLED_PROD }}\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_RANDOM_ROOT_PASSWORD=true\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_DATABASE=footyhints\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_USER=${{ secrets.MYSQL_USER_PROD }}\" >> /footyhints/docker/footyhints.env
          echo \"MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD_PROD }}\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_DB_URI=mysql://${{ secrets.MYSQL_USER_PROD }}:${{ secrets.MYSQL_PASSWORD_PROD }}@mysql/footyhints\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_VERSION=$VERSION\" >> /footyhints/docker/footyhints.env
          echo \"FOOTYHINTS_LEAGUE_ID=${{ vars.LEAGUE_ID }}\" >> /footyhints/docker/footyhints.env
        "

    - name: Stop running processes on remote host
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=accept-new" root@${{ secrets.FOOTYHINTS_SSH_HOST_PROD }} "
          cd /footyhints
          make stop
        "

    - name: Run containers build on remote host
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=accept-new" root@${{ secrets.FOOTYHINTS_SSH_HOST_PROD }} "
          cd /footyhints
          make build
        "

    - name: Run containers pre-clean on remote host
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=accept-new" root@${{ secrets.FOOTYHINTS_SSH_HOST_PROD }} "
          cd /footyhints
          make clean
        "

    - name: Run containers deploy on remote host
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=accept-new" root@${{ secrets.FOOTYHINTS_SSH_HOST_PROD }} "
          cd /footyhints
          make run
        "

    - name: Run cleanup on remote host
      run: |
        ssh -i ~/footyhints -o "StrictHostKeyChecking=accept-new" root@${{ secrets.FOOTYHINTS_SSH_HOST_PROD }} "
          rm -rf /footyhints
        "

    - name: Cleanup
      run: rm -rf ~/footyhints
