name: Github Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull all tags
        run: git fetch --tags -f

      # Set release information from the tag
      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set PREVIOUS_TAG env
        run: echo "PREVIOUS_TAG=$(git tag -l --sort=v:refname | tail -n2 | head -n1)" >> $GITHUB_ENV

      - name: Create release description
        id: release-description
        run: |
          DESCRIPTION=$(echo Changelog: https://github.com/pwnbus/footyhints/compare/$PREVIOUS_TAG...$RELEASE_VERSION)
          echo "RELEASE_DESCRIPTION=$DESCRIPTION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.release-description.outputs.RELEASE_DESCRIPTION }}
          draft: false
          prerelease: false
