name: Tests
on:
  push:
    branches: '*'
  # Run every night
  schedule:
    - cron: '0 0 * * *'
  # Allow for manual run
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: Build Tests
      run: make build-tests

    - name: Run tests
      run: make run-tests
